# Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

from ._caching import clear_all_caches
from .algorithms import (
    DoubleBuffer,
    SortOrder,
    binary_transform,
    exclusive_scan,
    histogram_even,
    inclusive_scan,
    make_binary_transform,
    make_exclusive_scan,
    make_histogram_even,
    make_inclusive_scan,
    make_merge_sort,
    make_radix_sort,
    make_reduce_into,
    make_segmented_reduce,
    make_segmented_sort,
    make_select,
    make_three_way_partition,
    make_unary_transform,
    make_unique_by_key,
    merge_sort,
    radix_sort,
    reduce_into,
    segmented_reduce,
    segmented_sort,
    select,
    three_way_partition,
    unary_transform,
    unique_by_key,
)
from .determinism import Determinism
from .iterators import (
    CacheModifiedInputIterator,
    ConstantIterator,
    CountingIterator,
    DiscardIterator,
    PermutationIterator,
    ReverseIterator,
    TransformIterator,
    TransformOutputIterator,
    ZipIterator,
)
from .op import OpKind
from .raw import (
    RawIterator,
    RawOp,
    TypeEnum,
    TypeInfo,
    bool_,
    float16,
    float32,
    float64,
    int8,
    int16,
    int32,
    int64,
    storage,
    uint8,
    uint16,
    uint32,
    uint64,
)
from .struct import gpu_struct

__all__ = [
    # Algorithms
    "binary_transform",
    "clear_all_caches",
    "DoubleBuffer",
    "exclusive_scan",
    "histogram_even",
    "inclusive_scan",
    "make_binary_transform",
    "make_exclusive_scan",
    "make_histogram_even",
    "make_inclusive_scan",
    "make_merge_sort",
    "make_radix_sort",
    "make_reduce_into",
    "make_segmented_reduce",
    "make_segmented_sort",
    "make_select",
    "make_three_way_partition",
    "make_unary_transform",
    "make_unique_by_key",
    "merge_sort",
    "radix_sort",
    "reduce_into",
    "segmented_reduce",
    "segmented_sort",
    "select",
    "three_way_partition",
    "unary_transform",
    "unique_by_key",
    # Iterators
    "CacheModifiedInputIterator",
    "ConstantIterator",
    "CountingIterator",
    "DiscardIterator",
    "PermutationIterator",
    "ReverseIterator",
    "TransformIterator",
    "TransformOutputIterator",
    "ZipIterator",
    # Operators
    "OpKind",
    # Determinism
    "Determinism",
    # Sorting
    "SortOrder",
    # Structs
    "gpu_struct",
    # Raw LTOIR Layer (for BYOC users)
    "RawOp",
    "RawIterator",
    # Type helpers
    "int8",
    "int16",
    "int32",
    "int64",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "float16",
    "float32",
    "float64",
    "bool_",
    "storage",
    "TypeInfo",
    "TypeEnum",
]
